CREATE TABLE IF NOT EXISTS partner_settings (id TEXT PRIMARY KEY,partner_name TEXT NOT NULL DEFAULT '',partner_email TEXT NOT NULL DEFAULT '',default_split_percent INTEGER NOT NULL DEFAULT 50,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS partner_products (product_id TEXT PRIMARY KEY,title TEXT NOT NULL,person TEXT NOT NULL,cost_cents INTEGER NOT NULL,sale_price_cents INTEGER,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS partner_entries (id TEXT PRIMARY KEY,operation_date TEXT NOT NULL,customer_name TEXT NOT NULL,order_protocol TEXT,product_id TEXT NOT NULL,product_title TEXT NOT NULL,charged_cents INTEGER NOT NULL,cost_cents INTEGER NOT NULL,net_cents INTEGER NOT NULL,admin_share_cents INTEGER NOT NULL,partner_share_cents INTEGER NOT NULL,pix_status TEXT NOT NULL DEFAULT 'pending',pix_paid_at TEXT,proof_name TEXT,proof_data TEXT,notes TEXT,created_at TEXT NOT NULL,updated_at TEXT);
CREATE INDEX IF NOT EXISTS idx_partner_entries_date ON partner_entries(operation_date DESC);
CREATE TABLE IF NOT EXISTS partner_closures (month TEXT PRIMARY KEY,total_partner_cents INTEGER NOT NULL,entry_count INTEGER NOT NULL,closed_at TEXT NOT NULL,closed_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS partner_login_codes (id TEXT PRIMARY KEY,email TEXT NOT NULL,code_hash TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS partner_sessions (id TEXT PRIMARY KEY,email TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
INSERT OR IGNORE INTO partner_settings(id,partner_name,partner_email,default_split_percent,updated_at) VALUES ('default','','',50,datetime('now'));
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-01','e-CPF A1','pf',6500,13500,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-02','e-CPF A1 - 3 meses','pf',2438,5000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-03','e-CPF A1 + Agilize Plus','pf',7500,15000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-04','e-CPF A1 - Emissão Online','pf',6900,14000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-05','e-CPF A1 - Emissão Online + Agilize Plus','pf',7900,15000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-06','e-CPF A1 + PLUS','pf',9000,18000,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-07','e-CPF A3 - 1 ano','pf',8000,15000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-08','e-CPF A3 - 1 ano + Agilize Plus','pf',9000,16000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-09','e-CPF A3 - 1 ano - Emissão Online','pf',8400,16000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-10','e-CPF A3 - 1 ano - Emissão Online + Agilize Plus','pf',9400,17000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-11','e-CPF A3 - 1 ano + PLUS','pf',9000,18000,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-12','e-CPF A3 - 2 anos','pf',9900,20000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-13','e-CPF A3 - 2 anos + Agilize Plus','pf',10900,21000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-14','e-CPF A3 - 2 anos - Emissão Online','pf',10300,21000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-15','e-CPF A3 - 2 anos - Emissão Online + Agilize Plus','pf',11300,22000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-16','e-CPF A3 - 2 anos + PLUS','pf',10900,22000,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-17','e-CPF A3 - 3 anos','pf',11900,28000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-18','e-CPF A3 - 3 anos - Emissão Online','pf',12300,30000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-19','e-CPF A3 - 3 anos + PLUS','pf',12900,30000,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-20','e-CPF A3 - SYN','pf',6500,13500,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-21','e-CPF A3 - SYN - Emissão Online','pf',6900,15000,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-22','e-CNPJ A1','pj',6500,21000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-23','e-CNPJ A1 - 3 meses','pj',2438,8000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-24','e-CNPJ A1 + Agilize Plus','pj',7500,25000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-25','e-CNPJ A1 - Emissão Online','pj',6900,22000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-26','e-CNPJ A1 - Emissão Online + Agilize Plus','pj',7900,25000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-27','e-CNPJ A1 + PLUS','pj',9000,26000,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-28','e-CNPJ A3 - 1 ano','pj',8000,22000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-29','e-CNPJ A3 - 1 ano + Agilize Plus','pj',9000,23000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-30','e-CNPJ A3 - 1 ano - Emissão Online','pj',8400,22000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-31','e-CNPJ A3 - 1 ano - Emissão Online + Agilize Plus','pj',9400,23000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-32','e-CNPJ A3 - 1 ano + PLUS','pj',9000,23000,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-33','e-CNPJ A3 - 2 anos','pj',14400,35000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-34','e-CNPJ A3 - 2 anos + Agilize Plus','pj',15400,36000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-35','e-CNPJ A3 - 2 anos - Emissão Online','pj',14800,35000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-36','e-CNPJ A3 - 2 anos - Emissão Online + Agilize Plus','pj',15800,36000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-37','e-CNPJ A3 - 2 anos + PLUS','pj',15400,36000,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-38','e-CNPJ A3 - 3 anos','pj',16300,40000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-39','e-CNPJ A3 - 3 anos - Emissão Online','pj',16700,40000,1);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-40','e-CNPJ A3 - 3 anos + PLUS','pj',17300,40000,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-41','Syn Pass - 2 anos','syn',0,NULL,0);
INSERT OR REPLACE INTO partner_products(product_id,title,person,cost_cents,sale_price_cents,active) VALUES ('cert-42','Syn Pass - Online 2 anos','syn',0,NULL,0);
