const encoder = new TextEncoder();
export const adminEmail = env => String(env.ADMIN_EMAIL || env.AGILIZE_NOTIFICATION_EMAIL || 'agilizecertificadora@gmail.com').trim().toLowerCase();
export const json = (data, status = 200, headers = {}) => Response.json(data, { status, headers: { 'Cache-Control': 'no-store', ...headers } });
export async function hash(value, secret) { const digest = await crypto.subtle.digest('SHA-256', encoder.encode(`${secret}:${value}`)); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, '0')).join(''); }
export function cookieValues(request, name) { const cookies = request.headers.get('Cookie') || ''; const values=[]; for (const part of cookies.split(';')) { const [key, ...value] = part.trim().split('='); if (key === name) values.push(decodeURIComponent(value.join('='))); } return values; }
export function cookieValue(request, name) { return cookieValues(request,name)[0] || ''; }
export function sessionCookie(token, maxAge = 28800, request = null) { let domain=''; try{const host=new URL(request?.url||'').hostname;if(host==='agilizecertificados.com.br'||host.endsWith('.agilizecertificados.com.br'))domain='; Domain=agilizecertificados.com.br'}catch{} return `agilize_admin=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}${domain}`; }
export async function requireAdmin(request, env) { if (!env.DB || !env.ADMIN_SESSION_SECRET) return null; for(const token of cookieValues(request,'agilize_admin')){if(!token)continue;const tokenHash=await hash(token,env.ADMIN_SESSION_SECRET);const session=await env.DB.prepare('SELECT id,email,expires_at FROM admin_sessions WHERE token_hash=? AND expires_at>? LIMIT 1').bind(tokenHash,new Date().toISOString()).first();if(session)return {...session,_token:token}}return null; }
export const clean = (value, max = 500) => String(value ?? '').trim().slice(0, max);
